---
- name: Hide user from GNOME login
  become: true
  notify: Restart gdm
  ansible.builtin.lineinfile:
    path: "/var/lib/AccountsService/users/{{ username }}"
    regexp: "^SystemAccount"
    line: "SystemAccount=true"
