---
argument_specs:
  main:
    options:
      cppreference_version:
        type: str
        default: "20250209"

      cppreference_target_dir:
        type: path
        default: "{{ ansible_facts['env']['HOME'] }}/cppreference{{ cppreference_version }}"

      cppreference_source:
        type: str
        default: "https://github.com/PeterFeicht/cppreference-doc/releases/download/v{{ cppreference_version }}/html-book-{{ cppreference_version }}.zip"
