---
- name: checkall
  hosts: checkall
  pre_tasks:
    - name: Ping
      ansible.builtin.ping:

  tasks:
    - name: Whoami osn
      ansible.builtin.command:
        cmd: whoami
      changed_when: false

    - name: Whoami root
      become: true
      become_user: root
      ansible.builtin.command:
        cmd: whoami
      changed_when: false

    - name: Get hostname
      tags: hostname
      ansible.builtin.command:
        cmd: hostname
      register: hostname
      changed_when: false

    - name: Print
      tags: hostname
      ansible.builtin.debug:
        var: hostname.stdout
