[all:vars]
ansible_connection=ssh
ansible_python_interpreter=/usr/bin/python3
; ansible_user=
; ansible_ssh_pass=
; ansible_become_password=

[control]
localhost ansible_connection=local

[contestants]
room01
room02

[room01]
192.168.4.[51:60]

[room02]
192.168.5.[51:60]
