---
- name: Create default OSN profile
  block:
    - name: Create parent directory
      ansible.builtin.file:
        path: "{{ app_firefox_config_basedir }}"
        state: directory
        mode: "0755"

    - name: Distribute default profiles
      ansible.builtin.copy:
        src: profiles.ini
        dest: "{{ app_firefox_config_basedir }}/profiles.ini"
        mode: "0644"

- name: Copy bookmarks
  when: app_firefox_bookmarks_file != ""
  block:
    - name: Create parent directory
      ansible.builtin.file:
        path: "{{ app_firefox_config_basedir }}/osnprofile.default"
        state: directory
        mode: "0755"

    - name: Copy bookmarks
      ansible.builtin.copy:
        src: "{{ app_firefox_bookmarks_file }}"
        dest: "{{ app_firefox_config_basedir }}/osnprofile.default/places.sqlite"
        mode: "0644"
