---
- name: Show user from GNOME login
  become: true
  notify: Restart gdm
  ansible.builtin.lineinfile:
    path: "/var/lib/AccountsService/users/{{ usermgmt_username }}"
    regexp: "^SystemAccount"
    line: "SystemAccount=false"
