---
- name: "Download google-chrome-stable"
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ app_chrome_source }}"
    dest: "{{ role_path }}/files/google-chrome-stable.deb"
    mode: "0644"

- name: Create package directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /opt/osn-packages
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Copy google-chrome-stable.deb
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "google-chrome-stable.deb"
    dest: "/opt/osn-packages/google-chrome-stable.deb"
    mode: "0644"

- name: Install google-chrome-stable
  become: true
  become_user: root
  ansible.builtin.apt:
    deb: "/opt/osn-packages/google-chrome-stable.deb"
