---
- name: Force kill process by user
  become: true
  ansible.builtin.command:
    cmd: "pkill -9 -u {{ username }}"
  register: pkill_result
  changed_when: pkill_result.rc == 1
  failed_when: pkill_result.rc > 1
  # rc: 0 any match, 1 no match, 2 invalid options, 3 internal error

- name: Remove user
  become: true
  notify: Restart gdm
  ansible.builtin.user:
    name: "{{ username }}"
    state: absent
    remove: true
