// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("browser.migration.version", 177);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("sidebar.visibility", "hide-on-close");
