---
- name: Workstation hardening
  hosts: contestants
  tasks:
    - name: Authorized control pubkey
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('file', '/home/lab-c-instruktur/.ssh/ansible.pub') }}" # TODO(AVM-Martin): check lookup

    - name: Only allow ssh by pubkey
      become: true
      notify: Restart ssh-server
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^\s*{{ item.key }}\b'
        line: "{{ item.key }} {{ item.value }}"
      with_items:
        - key: "PermitRootLogin"
          value: "prohibit-password"
        - key: "PubkeyAuthentication"
          value: "yes"
        - key: "PasswordAuthentication"
          value: "no"

  handlers:
    - name: Restart ssh-server
      become: true
      tags: always
      ansible.builtin.service:
        name: ssh
        state: restarted
