---
- name: "Download vscode {{ app_vscode_version }}"
  become: false
  delegate_to: localhost
  run_once: true
  ansible.builtin.get_url:
    url: "{{ app_vscode_source }}"
    dest: "{{ role_path }}/files/vscode-{{ app_vscode_version }}.deb"
    mode: "0644"

- name: Create package directory
  become: true
  become_user: root
  ansible.builtin.file:
    path: /opt/osn-packages
    owner: root
    group: root
    state: directory
    mode: "0755"

- name: Copy vscode.deb
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "vscode-{{ app_vscode_version }}.deb"
    dest: "/opt/osn-packages/vscode-{{ app_vscode_version }}.deb"
    mode: "0644"

- name: Install vscode
  become: true
  become_user: root
  ansible.builtin.apt:
    deb: "/opt/osn-packages/vscode-{{ app_vscode_version }}.deb"
